# -*- coding: utf-8 -*-
"""logistic-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bylbpNWX5VNX8RStjTyj8-9twwhV4IPZ
"""

# ============================================
# CELL 1: Install Required Packages
# ============================================
!pip install pandas scikit-learn nltk PyPDF2 python-docx beautifulsoup4

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from scipy.sparse import hstack
import nltk
from nltk.corpus import stopwords
import re
import pickle
from bs4 import BeautifulSoup

# ============================================
# CELL 3: Download NLTK Stopwords
# ============================================
import nltk
nltk.download("stopwords")

"""Load and Inspect Your Dataset"""

# ============================================
# CELL 4: Load Dataset
# ============================================
# Load CSV with resume text and scores
# Use engine='python' and on_bad_lines='skip' to handle malformed CSV (e.g. unclosed quotes)
try:
    df = pd.read_csv("Resume.csv", engine='python', on_bad_lines='skip')
except:
    df = pd.read_csv("/content/Resume.csv", engine='python', on_bad_lines='skip')

# Look at the data
print("Dataset shape:", df.shape)
print("\nFirst few rows:")
print(df.head())
print("\nColumn names:")
print(df.columns.tolist())

# ============================================
# CELL 5: Clean Column Names
# ============================================
# Make all column names lowercase and remove leading/trailing spaces
df.columns = df.columns.str.strip().str.lower()
print("Cleaned column names:", df.columns.tolist())

# ============================================
# CELL 6: Extract Text from HTML (if needed)
# ============================================
from bs4 import BeautifulSoup

def extract_text_from_html(html):
    """Extract plain text from HTML"""
    if pd.isna(html):
        return ""
    soup = BeautifulSoup(html, "html.parser")
    return soup.get_text(separator=" ", strip=True)

# If your data has resume_html column, extract text
if 'resume_html' in df.columns:
    df['resume_text'] = df['resume_html'].apply(extract_text_from_html)
    print("Extracted text from HTML")
elif 'resume_str' in df.columns:
    df['resume_text'] = df['resume_str']
    print("Using resume_str as resume_text")

# Check the result
print("\nSample resume text:")
print(df['resume_text'].iloc[0][:500])

# ============================================
# CELL 7: Text Cleaning Function
# ============================================
def clean_text(text):
    """Clean and preprocess text"""
    # Convert to string and lowercase
    text = str(text).lower()

    # Remove punctuation and special characters
    text = re.sub(r'[^a-z0-9\s]', '', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    # Remove stopwords
    text = " ".join([word for word in text.split()
                     if word not in stopwords.words("english")])

    return text

# ============================================
# CELL 8: Apply Text Cleaning
# ============================================
df['cleaned_text'] = df['resume_text'].apply(clean_text)

# Check result
print("Cleaned text sample:")
print(df[['resume_text', 'cleaned_text']].head())

# Check for empty texts
empty_count = df['cleaned_text'].str.strip().eq('').sum()
print(f"\nEmpty cleaned texts: {empty_count}")

# ============================================
# CELL 9: Advanced Resume Quality Scoring (Fine-tuned)
# ============================================
import re

def generate_better_score(text):
    """
    Fine-tuned resume quality scoring system for accurate grading.
    Returns score from 1-10 based on multiple quality dimensions.
    """

    if not text or len(text.strip()) < 50:
        return 1  # Empty / unreadable resume

    text_lower = text.lower()
    words = text.split()
    word_count = len(words)

    # ------------------------------------
    # 1. WORD COUNT (More granular)
    # ------------------------------------
    if word_count < 80:
        word_score = 1
    elif word_count < 150:
        word_score = 2
    elif word_count < 220:
        word_score = 4
    elif word_count < 300:
        word_score = 6
    elif 300 <= word_count <= 800:
        word_score = 9
    elif word_count <= 1100:
        word_score = 8
    else:
        word_score = 5

    # ------------------------------------
    # 2. PROFESSIONAL ACTION KEYWORDS (Expanded)
    # ------------------------------------
    professional_keywords = [
        'managed', 'developed', 'designed', 'led', 'implemented',
        'achieved', 'improved', 'created', 'analyzed', 'optimized',
        'coordinated', 'delivered', 'maintained', 'executed',
        'established', 'streamlined', 'reduced', 'increased', 'oversaw'
    ]
    keyword_hits = sum(1 for k in professional_keywords if k in text_lower)
    keyword_score = min(10, keyword_hits * 0.8)

    # ------------------------------------
    # 3. TECHNICAL/SKILL DEPTH (Broader - HR, Business, Tech)
    # ------------------------------------
    skill_terms = [
        'python', 'java', 'sql', 'aws', 'docker', 'kubernetes',
        'linux', 'git', 'api', 'database', 'cloud', 'ml', 'ai',
        'recruitment', 'onboarding', 'training', 'compliance',
        'excel', 'analytics', 'budget', 'project management'
    ]
    skill_hits = sum(1 for t in skill_terms if t in text_lower)
    tech_score = min(10, skill_hits * 0.7)

    # ------------------------------------
    # 4. STRUCTURE (Mandatory + Optional sections)
    # ------------------------------------
    required_sections = ['experience', 'education', 'skills']
    optional_sections = ['projects', 'certification', 'summary', 'objective', 'achievement']

    required_count = sum(1 for s in required_sections if s in text_lower)
    optional_count = sum(1 for s in optional_sections if s in text_lower)

    structure_score = min(10, (required_count * 2.5) + (optional_count * 0.5))

    # ------------------------------------
    # 5. QUANTITATIVE ACHIEVEMENTS (%, numbers)
    # ------------------------------------
    quant_patterns = re.findall(r'\d+%|\d+\s*(?:x|times|years?|months?)\b', text_lower)
    quant_score = min(10, len(quant_patterns) * 2) if quant_patterns else 3

    # ------------------------------------
    # 6. GIBBERISH / JUNK PENALTIES
    # ------------------------------------
    repeated_chars = len(re.findall(r'(.)\1{4,}', text))
    symbol_noise = len(re.findall(r'[@#$%^&*_=+<>]', text))
    penalty = min(3, repeated_chars + (symbol_noise // 10))

    # ------------------------------------
    # FINAL WEIGHTED SCORE
    # ------------------------------------
    final_score = (
        word_score * 0.20 +
        keyword_score * 0.25 +
        tech_score * 0.20 +
        structure_score * 0.25 +
        quant_score * 0.10
    ) - penalty

    score = max(1, min(10, round(final_score)))

    return score

# ============================================
# CELL 10: Generate Score Classes
# ============================================
df['score_class'] = df['cleaned_text'].apply(generate_better_score)

# Check distribution
print("Score class distribution:")
print(df['score_class'].value_counts().sort_index())

print("\nSample of scores:")
print(df[['resume_text', 'score_class']].head(10))

# ============================================
# CELL: Extract Hand-crafted Features (for better accuracy)
# ============================================
def extract_hand_features(text):
    """Extract rule-based features to combine with TF-IDF for finer grading."""
    if not text or len(text.strip()) < 10:
        return np.array([[0, 0, 0, 0]])
    text_lower = text.lower()
    words = text.split()
    # Normalized word count (0-1, peak around 400 words)
    wc = min(1.0, len(words) / 500)
    # Action keyword density
    action_kw = ['managed', 'developed', 'led', 'implemented', 'achieved', 'improved', 'created', 'analyzed']
    kw_count = min(1.0, sum(1 for k in action_kw if k in text_lower) / 6)
    # Section presence (experience, education, skills)
    sections = ['experience', 'education', 'skills', 'summary']
    sec_count = sum(1 for s in sections if s in text_lower) / 4
    # Quantitative metrics
    quant = len(re.findall(r'\d+%|\d+\s*(?:years?|months?)\b', text_lower))
    quant_norm = min(1.0, quant / 5)
    return np.array([[wc, kw_count, sec_count, quant_norm]])

# ============================================
# CELL 11: Prepare Features and Labels
# ============================================
# Features and labels
X = df['cleaned_text']
y = df['score_class']

print(f"Total samples: {len(X)}")
print(f"Score distribution:\n{y.value_counts().sort_index()}")

# Check how many samples per score
print(y.value_counts())

# ============================================
# CELL 12: Train-Test Split (FINAL FIX)
# ============================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training set size:", X_train.shape[0])
print("Test set size:", X_test.shape[0])

# ============================================
# CELL 13: Enhanced Vectorization with TF-IDF + Hand Features
# ============================================
# Create TF-IDF with unigrams + bigrams + trigrams for better context
vectorizer = TfidfVectorizer(
    max_features=8000,
    min_df=2,
    max_df=0.85,
    ngram_range=(1, 3),  # Unigrams, bigrams, trigrams
    sublinear_tf=True,    # Use log(tf) for better scaling
    strip_accents='unicode'
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Add hand-crafted features for finer grading
X_train_hand = np.vstack([extract_hand_features(t) for t in X_train])
X_test_hand = np.vstack([extract_hand_features(t) for t in X_test])

# Combine TF-IDF + hand features
X_train_combined = hstack([X_train_tfidf, X_train_hand])
X_test_combined = hstack([X_test_tfidf, X_test_hand])

print("TF-IDF shape:", X_train_tfidf.shape)
print("Combined shape:", X_train_combined.shape)
print("Vocabulary size:", len(vectorizer.vocabulary_))

# ============================================
# CELL 14: Train Logistic Regression Model (with class weights)
# ============================================
# Use class_weight='balanced' to handle imbalanced classes
log_model = LogisticRegression(
    max_iter=2000,
    random_state=42,
    class_weight='balanced',  # Handles imbalanced score distribution
    C=1.0,                   # Regularization strength
    solver='lbfgs',
    multi_class='multinomial'
)
log_model.fit(X_train_combined, y_train)

print("Model training complete!")
print("Classes found:", log_model.classes_)

# ============================================
# CELL 15: Evaluate Model
# ============================================
# Make predictions (using combined features)
y_pred = log_model.predict(X_test_combined)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

# ============================================
# CELL 16: Prediction Function (0-100 scale) + Grade Level
# ============================================
def predict_professional_score(text):
    """
    Predict resume score from 0-100 (uses TF-IDF + hand features)
    """
    clean = clean_text(text)
    vec_tfidf = vectorizer.transform([clean])
    vec_hand = extract_hand_features(text)
    vec_combined = hstack([vec_tfidf, vec_hand])
    probs = log_model.predict_proba(vec_combined)[0]
    classes = log_model.classes_
    score_0_100 = sum(p * c * 10 for p, c in zip(probs, classes))
    return round(score_0_100)

def grade_resume(text):
    """
    Grade resume and return (score_0_100, grade_level, needs_enhancement)
    Grade levels: Poor (<65), Average (65-75), Good (75-82), Excellent (>82)
    Average resumes automatically get enhancement.
    """
    score = predict_professional_score(text)
    if score < 65:
        grade = "Poor"
        needs_enhancement = True
    elif score < 75:
        grade = "Average"
        needs_enhancement = True   # Enhance average resumes
    elif score < 82:
        grade = "Good"
        needs_enhancement = False
    else:
        grade = "Excellent"
        needs_enhancement = False
    return score, grade, needs_enhancement

# ============================================
# CELL 17: Generate Final Scores (0-100)
# ============================================
df['score'] = df['resume_text'].apply(predict_professional_score)

print("Final scores generated!")
print("\nScore statistics:")
print(df['score'].describe())

print("\nSample scores:")
print(df[['resume_text', 'score_class', 'score']].head(10))

"""## Resume Enhancement for Average-Graded Resumes

When a resume receives an **Average** grade (score 65-75), the system automatically:
1. **Identifies missing sections** (Summary, Experience, Education, Skills)
2. **Suggests stronger action verbs** (e.g., "did" → "Executed")
3. **Recommends quantitative metrics** (%, numbers, impact)
4. **Generates an enhanced version** with template sections where needed
"""

# ============================================
# CELL: Resume Enhancement Module (for Average-graded resumes)
# ============================================

def enhance_resume(text):
    """
    Enhance a resume that received average grading.
    Returns enhanced version with suggestions and improvements.
    """
    text_lower = text.lower()
    enhancements = []
    enhanced_text = text

    # 1. Check for missing sections
    required_sections = {
        'summary': ['professional summary', 'summary', 'executive summary', 'profile'],
        'experience': ['experience', 'work experience', 'employment', 'professional experience'],
        'education': ['education', 'academic', 'degree', 'qualification'],
        'skills': ['skills', 'technical skills', 'competencies', 'expertise']
    }

    missing_sections = []
    for section_name, keywords in required_sections.items():
        if not any(kw in text_lower for kw in keywords):
            missing_sections.append(section_name)

    if missing_sections:
        enhancements.append(f"ADD: Missing sections - {', '.join(missing_sections)}")

    # 2. Action verb suggestions (weak verbs to replace)
    weak_verbs = {
        'did': 'Executed', 'made': 'Developed', 'helped': 'Supported',
        'worked on': 'Delivered', 'used': 'Leveraged', 'got': 'Achieved',
        'handled': 'Managed', 'did work': 'Implemented'
    }

    action_verb_suggestions = []
    for weak, strong in weak_verbs.items():
        if weak in text_lower:
            action_verb_suggestions.append(f"Replace '{weak}' with '{strong}'")

    if action_verb_suggestions:
        enhancements.append("IMPROVE: " + "; ".join(action_verb_suggestions[:3]))

    # 3. Add quantitative metrics if sparse
    import re
    quant_count = len(re.findall(r'\d+%|\d+\s*(?:x|times|years?|months?)\b', text_lower))
    if quant_count < 2:
        enhancements.append("ADD: Include quantitative achievements (e.g., 'Increased X by 25%', 'Reduced costs by $Y')")

    # 4. Build enhanced resume with template additions
    enhanced_parts = [enhanced_text]

    # Add professional summary template if missing
    if 'summary' in missing_sections or 'profile' in missing_sections:
        summary_template = "\n\nPROFESSIONAL SUMMARY\n" + "-"*40 + "\nResults-driven professional with proven experience. Skilled in [ADD YOUR KEY SKILLS]. Demonstrated success in [ADD KEY ACHIEVEMENT]. Seeking to leverage expertise to [ADD GOAL].\n"
        enhanced_parts.append(summary_template)

    # Add skills section template if missing
    if 'skills' in missing_sections:
        skills_template = "\n\nSKILLS\n" + "-"*40 + "\n• [Technical Skill 1]  • [Technical Skill 2]  • [Technical Skill 3]\n• [Soft Skill 1]  • [Soft Skill 2]\n"
        enhanced_parts.append(skills_template)

    enhanced_text = "".join(enhanced_parts)

    return {
        'enhanced_resume': enhanced_text,
        'suggestions': enhancements,
        'missing_sections': missing_sections
    }

def grade_and_enhance(text):
    """
    Full pipeline: Grade resume, and if average, return enhanced version.
    """
    score, grade, needs_enhancement = grade_resume(text)

    result = {
        'score': score,
        'grade': grade,
        'needs_enhancement': needs_enhancement
    }

    if needs_enhancement and grade == "Average":
        enhancement = enhance_resume(text)
        result['enhanced_resume'] = enhancement['enhanced_resume']
        result['suggestions'] = enhancement['suggestions']
        result['missing_sections'] = enhancement['missing_sections']

    return result

# ============================================
# CELL: Test Grade + Enhance Pipeline
# ============================================
# Test with resumes of varying quality
test_cases = [
    # Average - short, minimal
    """John Doe
    Software Developer. I did work on web apps. Used Python and Java.
    Education: BS Computer Science.""",

    # Good resume
    """Senior Software Engineer with 8+ years experience.
    Summary: Led development of enterprise applications. Managed team of 5.
    Skills: Python, Java, SQL, AWS, Docker. Achieved 30% performance improvement.
    Experience: Developed scalable systems. Implemented CI/CD pipelines.
    Education: MS Computer Science.""",

    # Poor - very short
    "Contact me. I have experience."
]

print("=" * 70)
print("RESUME GRADING + ENHANCEMENT PIPELINE")
print("=" * 70)

for i, resume in enumerate(test_cases, 1):
    result = grade_and_enhance(resume)
    print(f"\n--- Test {i} ---")
    print(f"Score: {result['score']}/100  |  Grade: {result['grade']}")
    print(f"Needs Enhancement: {result['needs_enhancement']}")

    if result.get('suggestions'):
        print("\nEnhancement Suggestions:")
        for s in result['suggestions']:
            print(f"  • {s}")

    if result.get('enhanced_resume') and result['grade'] == "Average":
        print("\nEnhanced Resume Preview (first 300 chars):")
        print(result['enhanced_resume'][:300] + "...")

# ============================================
# CELL 18: Test with Sample Texts
# ============================================
# Test predictions with various quality resumes
test_texts = [
    # Low quality - very short
    "I have experience. Contact me.",

    # Medium quality - some details
    "Software Engineer with 3 years experience. Skills: Python, Java. "
    "Worked on web applications. Bachelor's degree in Computer Science.",

    # High quality - comprehensive
    """Experienced System Administrator with 10+ years managing enterprise networks
    and cloud infrastructure. Technical Skills: AWS, Python, SQL, Docker, Kubernetes,
    Linux/Windows Server, VPN configuration, firewall management, security protocols.
    Professional Experience: Led team of 5 engineers, implemented security measures
    reducing vulnerabilities by 40%, managed migration to cloud infrastructure.
    Education: Bachelor of Science in Computer Science from State University.
    Certifications: CISSP, CCNA, AWS Solutions Architect. Achievements: Reduced
    system downtime by 60%, improved network performance, developed automated
    monitoring solutions."""
]

print("\nTest Predictions:")
print("=" * 60)
for i, text in enumerate(test_texts, 1):
    score = predict_professional_score(text)
    word_count = len(text.split())
    print(f"\nTest {i}:")
    print(f"  Words: {word_count}")
    print(f"  Score: {score}/100")
    print(f"  Text preview: {text[:80]}...")

# ============================================
# CELL 19: Save Model and Vectorizer
# ============================================
import pickle

# Save trained model
with open("logistic_model.pkl", "wb") as f:
    pickle.dump(log_model, f)

# Save vectorizer
with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("\n" + "="*60)
print("Model and vectorizer saved successfully!")
print("Files created:")
print("  - logistic_model.pkl")
print("  - vectorizer.pkl")
print("="*60)

# ============================================
# CELL 20: Verify Saved Files
# ============================================
!ls -lh *.pkl


# ============================================
# CELL 21: Test Loading Saved Model
# ============================================
# Load and test the saved model
with open("logistic_model.pkl", "rb") as f:
    loaded_model = pickle.load(f)

with open("vectorizer.pkl", "rb") as f:
    loaded_vectorizer = pickle.load(f)

print("Model loaded successfully!")

# Quick test (use combined features like predict_professional_score)
test_text = "Experienced software developer with Python and Java skills."
clean = clean_text(test_text)
vec_tfidf = loaded_vectorizer.transform([clean])
vec_hand = extract_hand_features(test_text)
vec = hstack([vec_tfidf, vec_hand])
prediction = loaded_model.predict(vec)[0]
probs = loaded_model.predict_proba(vec)[0]
score = sum(p * c * 10 for p, c in zip(probs, loaded_model.classes_))

print(f"\nTest prediction:")
print(f"  Text: {test_text}")
print(f"  Predicted class: {prediction}")
print(f"  Score: {round(score)}/100")
print("\nModel is ready to use!")

