-- Paste this entire file into Neon → SQL Editor → Run
-- Inserts sample rows into `jobs` (and optional `skills` links).
-- Safe to run once; delete from jobs WHERE company_name LIKE '%(sample)%' to remove samples.

-- Optional: ensure pgcrypto for gen_random_uuid (Neon usually has it)
-- SELECT gen_random_uuid();

INSERT INTO jobs (
  id,
  job_title,
  company_name,
  location,
  employment_type,
  job_description,
  application_deadline,
  contact_email,
  salary_min,
  salary_max,
  is_remote,
  key_responsibilities,
  requirements,
  preferred_qualifications,
  years_of_experience,
  benefits_perks,
  status,
  created_at,
  updated_at,
  created_by_id
) VALUES
(
  gen_random_uuid(),
  'Frontend Developer (React)',
  'Ansari Tech',
  'Kathmandu, Nepal',
  'full_time',
  'Build responsive UIs with React and Vite. Own features from design to deploy; collaborate with API and QA teams.',
  CURRENT_DATE + 30,
  'careers@ansaritech.example',
  80000,
  120000,
  true,
  '- Implement responsive layouts and reusable components.
- Integrate REST APIs with solid loading/error handling.
- Improve performance and accessibility (WCAG basics).',
  '2+ years React; strong JavaScript (ES6+); Git and modern tooling.',
  'TypeScript; React Router; testing with Vitest or Jest.',
  '2–5 years',
  'Health stipend, learning budget, flexible hours, remote-friendly.',
  'active',
  NOW(),
  NOW(),
  NULL
),
(
  gen_random_uuid(),
  'Backend Engineer (Django)',
  'Cloud Nepal',
  'Remote',
  'contract',
  'Maintain Django REST APIs, PostgreSQL on Neon, JWT auth, and CI/CD pipelines.',
  CURRENT_DATE + 21,
  'hr@cloudnepal.example',
  70000,
  100000,
  true,
  '- Design and document REST endpoints.
- Optimize SQL and indexes; review migrations.
- Support light on-call for production issues.',
  '3+ years Python; 2+ years Django in production; PostgreSQL experience.',
  'Neon/AWS; pytest; Docker.',
  '3+ years',
  'Monthly contract rate; hardware stipend; flexible schedule.',
  'active',
  NOW(),
  NOW(),
  NULL
),
(
  gen_random_uuid(),
  'Data Analyst Intern',
  'Retail Analytics Co.',
  'Pokhara',
  'internship',
  'Six-month internship: KPI reports, SQL queries, Excel/Power BI under mentorship.',
  CURRENT_DATE + 14,
  'interns@retailanalytics.example',
  15000,
  25000,
  false,
  '- Weekly KPI reports; validate data quality.
- Ad-hoc SQL and spreadsheet models.',
  'Bachelor’s in quantitative field; strong Excel; eager to learn SQL.',
  'Python or R coursework is a plus.',
  '0–1 year',
  'Stipend, certificate, mentorship.',
  'active',
  NOW(),
  NOW(),
  NULL
),
(
  gen_random_uuid(),
  'DevOps Engineer (Junior)',
  'Ansari Tech',
  'Kathmandu (hybrid)',
  'full_time',
  'Keep CI/CD, monitoring, and deploys healthy. Work with backend on automation and runbooks.',
  CURRENT_DATE + 45,
  'platform@ansaritech.example',
  55000,
  85000,
  false,
  '- Maintain GitHub Actions workflows.
- Monitor logs and uptime; document incidents.',
  '1+ year Linux; scripting (Bash/Python); basic networking.',
  'Docker/Kubernetes interest; observability tools.',
  '1–3 years',
  'Hybrid schedule, learning budget, health after probation.',
  'active',
  NOW(),
  NOW(),
  NULL
);

-- More sample jobs (run after the first block, or run this file as a whole — duplicate titles will error)
INSERT INTO jobs (
  id, job_title, company_name, location, employment_type, job_description,
  application_deadline, contact_email, salary_min, salary_max, is_remote,
  key_responsibilities, requirements, preferred_qualifications, years_of_experience,
  benefits_perks, status, created_at, updated_at, created_by_id
) VALUES
(
  gen_random_uuid(),
  'Mobile Developer (Flutter)',
  'Pocket Apps Nepal',
  'Lalitpur',
  'full_time',
  'Cross-platform Flutter apps for fintech and education. Flutter, REST APIs, app store releases.',
  CURRENT_DATE + 28,
  'mobile@pocketapps.example',
  65000,
  95000,
  true,
  E'- Build Flutter screens and state.\n- Integrate auth and payments.\n- Fix production crashes.',
  '1+ years Flutter or mobile; Dart; Git.',
  'Firebase; push notifications.',
  '1–4 years',
  'EPF, bonuses, device allowance, hybrid.',
  'active',
  NOW(),
  NOW(),
  NULL
),
(
  gen_random_uuid(),
  'UX/UI Designer',
  'Creative Studio Kathmandu',
  'Kathmandu',
  'full_time',
  'Wireframes, Figma mockups, and handoff to developers for startups and NGOs.',
  CURRENT_DATE + 35,
  'design@csk.example',
  45000,
  75000,
  false,
  E'- Discovery and user flows.\n- Design system maintenance.\n- Weekly sprints with PM/engineering.',
  'Portfolio; 2+ years Figma; responsive layouts.',
  'HTML/CSS awareness; accessibility.',
  '2+ years',
  'Creative Fridays, conference budget, insurance.',
  'active',
  NOW(),
  NOW(),
  NULL
),
(
  gen_random_uuid(),
  'QA Engineer (Automation)',
  'Quality First QA',
  'Remote',
  'contract',
  'Playwright/Cypress automation, CI integration, Jira triage for SaaS clients.',
  CURRENT_DATE + 20,
  'qa@qualityfirst.example',
  60000,
  90000,
  true,
  E'- E2E and API tests.\n- Defect tracking.\n- Reduce flaky tests.',
  'Test automation; JavaScript or Python; CI.',
  'Perf/a11y testing; Docker.',
  '2+ years',
  'Remote, flexible contract.',
  'active',
  NOW(),
  NOW(),
  NULL
),
(
  gen_random_uuid(),
  'Digital Marketing Specialist',
  'Growth Nepal Digital',
  'Kathmandu',
  'full_time',
  'Meta/Google Ads, SEO, content calendars; weekly CPL/ROAS reporting.',
  CURRENT_DATE + 25,
  'careers@growthnepal.example',
  35000,
  55000,
  false,
  E'- Ad spend optimization.\n- Creative coordination.\n- GA4 and Search Console.',
  '1+ year ads; copy skills; analytics.',
  'Google Ads cert; e-commerce brands.',
  '1–3 years',
  'Bonuses, outings, workshops.',
  'active',
  NOW(),
  NOW(),
  NULL
),
(
  gen_random_uuid(),
  'Cybersecurity Analyst',
  'SecureNet Nepal',
  'Biratnagar',
  'full_time',
  'SIEM monitoring, vulnerability assessments, incident response for enterprise clients.',
  CURRENT_DATE + 40,
  'soc@securenet.example',
  70000,
  110000,
  false,
  E'- Alert triage and incidents.\n- Phishing simulations.\n- Hardening checklists.',
  'Networking/OS basics; blue team interest.',
  'Security+/CEH; Splunk/Elastic.',
  '2+ years',
  'Cert sponsorship, on-call pay, insurance.',
  'active',
  NOW(),
  NOW(),
  NULL
),
(
  gen_random_uuid(),
  'Full Stack Developer (MERN)',
  'StartupLab Asia',
  'Remote',
  'freelance',
  'MVPs with MongoDB, Express, React, Node — fast iterations and demos.',
  CURRENT_DATE + 18,
  'build@startuplab.example',
  90000,
  140000,
  true,
  E'- APIs and React dashboards.\n- Deploy to cloud.\n- Weekly stakeholder demos.',
  'MERN portfolio; async communication.',
  'TypeScript; Next.js; Stripe.',
  '3+ years',
  'Project rates; flexible; referrals.',
  'active',
  NOW(),
  NOW(),
  NULL
),
(
  gen_random_uuid(),
  'Technical Writer (API Docs)',
  'Docs & Co.',
  'Remote',
  'part_time',
  'OpenAPI specs, developer guides, changelogs for B2B APIs.',
  CURRENT_DATE + 22,
  'writers@docsco.example',
  25000,
  40000,
  true,
  E'- MkDocs/Markdown sites.\n- Review API PRs.\n- Partner developer tests.',
  'Strong English; software documentation experience.',
  'REST/JSON; OpenAPI.',
  '1+ years',
  'Part-time async, contract renewal.',
  'active',
  NOW(),
  NOW(),
  NULL
),
(
  gen_random_uuid(),
  'HR & Talent Partner',
  'Ansari Tech',
  'Kathmandu',
  'full_time',
  'Full-cycle tech recruiting: sourcing, interviews, offers, onboarding.',
  CURRENT_DATE + 32,
  'people@ansaritech.example',
  40000,
  65000,
  false,
  E'- LinkedIn and referral sourcing.\n- Interview coordination.\n- Onboarding and branding.',
  '2+ years tech recruiting or HR with tech exposure.',
  'ATS; Nepal labor basics.',
  '2–5 years',
  'Hybrid, learning stipend, events.',
  'active',
  NOW(),
  NOW(),
  NULL
);

-- Verify
SELECT job_title, company_name, location, status, application_deadline
FROM jobs
ORDER BY created_at DESC;
